### ISSUE TITLE
NextPVR v5 unsupported

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin-plugin-nextpvr#7]
The plugin currently only supports NextPVR v4
As the first stable v5 release is out now, maybe someone can add support for the new version.
https://forums.nextpvr.com/showthread.php?tid=60574

**Comment by emveepee** [comment]
I did the Emby port I have made a few posts on the jellyfin and NextPVR forum and so far no one has seemed to care.  If you are actually using v4 and want to do most of the testing v5 join in the discussion here. https://forums.nextpvr.com/showthread.php?tid=60508 

In my open this is not really an issue though since I don't plan on making the old version support both API's and plan on a separate plugin.  Very little of the code can be reused.

**Comment by Nickbert7** [comment]
This sounds good, I'll join the conversation in the NPVR forum and close the issue here.
Thank you 👍
